// Draft generated by /e2e-check on 2026-05-20. Refine selectors and assertions, then remove @draft tag and rename to .spec.ts
import { expect, test } from "@playwright/test";

test.describe(
  "Учитель генерирует пригласительную ссылку для ученика",
  { tag: ["@draft", "@critical", "@students"] },
  () => {
    test("учитель открывает карточку ученика, выпускает invite и копирует ссылку", async ({
      page,
      context,
    }) => {
      // TODO: войти как учитель (storageState).
      // TODO: создать ученика через REST или UI, чтобы получить детерминированный id.
      await context.grantPermissions(["clipboard-read", "clipboard-write"]);

      await page.goto("/students");
      await page.getByRole("button", { name: /TODO_STUDENT_NAME/ }).click();

      // InvitationManager рендерится внутри StudentViewDialog.
      // TODO: подобрать стабильный селектор для блока (например data-testid).
      await page
        .getByRole("button", { name: /выпустить.*ссылк|пригласи/i })
        .click();

      // После генерации появляется readonly TextField с URL + кнопка «Скопировать».
      const inviteField = page.getByRole("textbox", { name: /ссылк/i });
      await expect(inviteField).toBeVisible();
      await expect(inviteField).toHaveValue(/\/student-invite\//);

      await page.getByRole("button", { name: /скопировать/i }).click();

      // TODO: проверить clipboard через handle.evaluate(() => navigator.clipboard.readText()).
    });

    test("учитель отзывает выпущенную ссылку, статус сменяется на REVOKED", async ({
      page,
    }) => {
      // TODO: подготовить ученика и PENDING invitation через REST.
      await page.goto("/students");
      await page.getByRole("button", { name: /TODO_STUDENT_NAME/ }).click();

      await page.getByRole("button", { name: /отозв/i }).click();

      // После отзыва текст состояния должен поменяться, например на «Ссылка отозвана».
      await expect(page.getByText(/отозван/i)).toBeVisible();
    });
  }
);
