// Draft generated by /e2e-check on 2026-05-20. Refine selectors and assertions, then remove @draft tag and rename to .spec.ts
import { expect, test } from "@playwright/test";

test.describe(
  "Ученик смотрит свои настройки",
  { tag: ["@draft", "@regression", "@lessons"] },
  () => {
    test("ученик видит имя, email, статус верификации и имя учителя", async ({
      page,
    }) => {
      // TODO: подготовить ученика «Пётр Сидоров», учитель «Анна Петрова»,
      // email подтверждён.
      await page.goto("/student/cabinet/settings");

      await expect(page.getByText("Пётр Сидоров")).toBeVisible();
      await expect(page.getByText(/Email подтверждён/i)).toBeVisible();
      await expect(page.getByText("Анна Петрова")).toBeVisible();
    });

    test("если карточка ученика удалена у учителя — settings показывает плейсхолдер", async ({
      page,
    }) => {
      // TODO: подготовить через REST: создать ученика → выдать invite → register →
      // удалить карточку студента у учителя. StudentUser остаётся, но student=null.
      await page.goto("/student/cabinet/settings");

      await expect(
        page.getByText(/Связь с преподавателем прекращена/i)
      ).toBeVisible();
    });
  }
);
