// Draft generated by /e2e-check on 2026-05-20. Refine selectors and assertions, then remove @draft tag and rename to .spec.ts
import { expect, test } from "@playwright/test";

test.describe(
  "Ученик видит своё расписание в кабинете",
  { tag: ["@draft", "@critical", "@lessons"] },
  () => {
    test("ученик открывает schedule и видит только свои уроки", async ({
      page,
    }) => {
      // TODO: подготовить через REST 2-х учителей, у каждого по 1 ученику,
      // и по 1 уроку у каждого. Логинимся за ученика учителя А.
      await page.goto("/student/cabinet/schedule");

      await expect(page).toHaveURL(/\/student\/cabinet\/schedule$/);

      // Видит свой урок (TODO: вставить точный subject из подготовленных данных).
      await expect(page.getByText(/TODO_SUBJECT_OF_OWN_LESSON/)).toBeVisible();

      // НЕ видит чужой урок учителя Б (cross-tenant isolation на уровне API).
      await expect(
        page.getByText(/TODO_SUBJECT_OF_OTHER_STUDENT_LESSON/)
      ).toHaveCount(0);

      // На карточке урока — только разрешённые поля (subject, time, status),
      // без price/notes/homework (см. studentCabinet.helpers).
      // TODO: добавить assert на отсутствие текста "Цена" / "Оплачено" / "Заметки".
    });

    test("ученик переключает неделю и видит уроки следующей", async ({
      page,
    }) => {
      // TODO: подготовить два урока на разных неделях.
      await page.goto("/student/cabinet/schedule");

      // TODO: подобрать стабильный селектор для кнопки «Следующая неделя»
      // (StudentWeeklyView навигация — посмотреть data-testid или aria-label).
      await page.getByRole("button", { name: /следующая|next|>/i }).click();

      await expect(page.getByText(/TODO_SUBJECT_NEXT_WEEK/)).toBeVisible();
    });
  }
);
