// Draft generated by /e2e-check on 2026-05-20. Refine selectors and assertions, then remove @draft tag and rename to .spec.ts
import { expect, test } from "@playwright/test";

test.describe(
  "Расписание ученика обновляется в реальном времени",
  { tag: ["@draft", "@regression", "@pwa"] },
  () => {
    test("учитель создаёт урок — у ученика он появляется без перезагрузки страницы", async ({
      browser,
    }) => {
      // TODO: подготовить пару tutor+student с активным invitation + регистрацией.
      const tutorContext = await browser.newContext({
        // TODO: storageState учителя
      });
      const studentContext = await browser.newContext({
        // TODO: storageState ученика
      });
      const tutorPage = await tutorContext.newPage();
      const studentPage = await studentContext.newPage();

      // Ученик открывает расписание — должен подняться WebSocket /ws/student.
      await studentPage.goto("/student/cabinet/schedule");
      await expect(studentPage.getByText(/Расписание/i)).toBeVisible();

      // Учитель создаёт урок для этого ученика.
      await tutorPage.goto("/lessons");
      await tutorPage.getByRole("button", { name: "Добавить урок" }).click();
      // TODO: заполнить форму урока — subject, время, выбрать нужного ученика.
      await tutorPage.getByRole("button", { name: "Сохранить" }).click();

      // У ученика урок появляется в течение нескольких секунд без перезагрузки.
      await expect(
        studentPage.getByText(/TODO_SUBJECT_OF_NEW_LESSON/)
      ).toBeVisible({ timeout: 5000 });

      await tutorContext.close();
      await studentContext.close();
    });

    test("учитель удаляет урок — у ученика он исчезает без перезагрузки", async ({
      browser,
    }) => {
      // TODO: подготовить один существующий урок ученика.
      const tutorContext = await browser.newContext({});
      const studentContext = await browser.newContext({});
      const tutorPage = await tutorContext.newPage();
      const studentPage = await studentContext.newPage();

      await studentPage.goto("/student/cabinet/schedule");
      await expect(
        studentPage.getByText(/TODO_SUBJECT_OF_EXISTING_LESSON/)
      ).toBeVisible();

      // Учитель удаляет урок через UI.
      await tutorPage.goto("/lessons");
      // TODO: открыть урок и удалить.

      await expect(
        studentPage.getByText(/TODO_SUBJECT_OF_EXISTING_LESSON/)
      ).toHaveCount(0, { timeout: 5000 });

      await tutorContext.close();
      await studentContext.close();
    });
  }
);
