// Draft generated by /e2e-check on 2026-05-20. Refine selectors and assertions, then remove @draft tag and rename to .spec.ts
import { expect, test } from "@playwright/test";

test.describe(
  "Регистрация ученика по приглашению",
  { tag: ["@draft", "@critical", "@auth"] },
  () => {
    test("ученик открывает инвайт-ссылку, регистрируется и попадает в кабинет", async ({
      page,
    }) => {
      // TODO: подготовить тестовые данные — учитель + ученик + PENDING invitation через REST
      // POST /api/auth/login (учитель) → POST /api/students → POST /api/students/:id/invitations
      // Достать inviteUrl из ответа и извлечь token.
      const inviteToken = "TODO_REPLACE_WITH_GENERATED_TOKEN";

      await page.goto(`/student-invite/${inviteToken}`);

      // TODO: подобрать стабильный селектор для формы (getByLabel должно сработать —
      // лейблы заданы в StudentInviteForm.tsx).
      await page.getByLabel("ФИО").fill("Пётр Сидоров");
      await page.getByLabel("Email").fill(`student-${Date.now()}@example.com`);
      await page.getByLabel("Пароль", { exact: true }).fill("StrongPass1");
      await page.getByLabel("Подтверждение пароля").fill("StrongPass1");

      await page.getByRole("button", { name: "Зарегистрироваться" }).click();

      // После успеха — редирект в кабинет + баннер «Подтвердите email».
      await expect(page).toHaveURL(/\/student\/cabinet\/schedule$/);
      await expect(page.getByText(/Подтвердите email/i)).toBeVisible();
    });
  }
);
