// Draft generated by /e2e-check on 2026-05-20. Refine selectors and assertions, then remove @draft tag and rename to .spec.ts
import { expect, test } from "@playwright/test";

test.describe(
  "Невалидная инвайт-ссылка ученика",
  { tag: ["@draft", "@regression", "@auth"] },
  () => {
    test("ученик открывает ссылку с неизвестным токеном и видит сообщение", async ({
      page,
    }) => {
      await page.goto("/student-invite/totally-unknown-token");

      // TODO: подобрать стабильный селектор для error-state (StudentInvitePage показывает
      // SpacedAlert с текстом «Ссылка недействительна или истекла» — точный текст
      // уточнить в frontend/src/pages/studentInvite/StudentInvitePage.tsx).
      await expect(
        page.getByText(/недействительна|истекла|неверн/i)
      ).toBeVisible();

      // Форма регистрации не должна показываться.
      await expect(
        page.getByRole("button", { name: "Зарегистрироваться" })
      ).toHaveCount(0);
    });

    test("ученик открывает ссылку с уже использованным токеном и видит сообщение", async ({
      page,
    }) => {
      // TODO: подготовить USED invitation через REST (как в quickstart):
      // 1) выдать invitation, 2) выполнить /api/student-auth/register с этим токеном,
      // 3) теперь токен USED — открыть ту же ссылку повторно.
      const usedToken = "TODO_GENERATE_AND_CONSUME";

      await page.goto(`/student-invite/${usedToken}`);

      await expect(
        page.getByText(/недействительна|истекла|использован/i)
      ).toBeVisible();
    });
  }
);
