// Draft generated by /e2e-check on 2026-05-20. Refine selectors and assertions, then remove @draft tag and rename to .spec.ts
import { expect, test } from "@playwright/test";

test.describe(
  "Подтверждение email ученика",
  { tag: ["@draft", "@regression", "@auth"] },
  () => {
    test("ученик вводит 6-значный код из письма и баннер исчезает", async ({
      page,
    }) => {
      // TODO: зарегистрировать ученика + перехватить отправленный код
      // (sendStudentVerificationEmail в test-окружении пишет в mock — достать оттуда).
      const verificationCode = "TODO_FROM_MOCK_INBOX";

      // TODO: войти как ученик (storageState или login через UI).
      await page.goto("/student/cabinet/schedule");

      await expect(page.getByText(/Подтверждение email/i)).toBeVisible();

      await page.getByLabel("Код").fill(verificationCode);
      await page.getByRole("button", { name: "Подтвердить" }).click();

      // Баннер должен исчезнуть, признак isEmailVerified=true.
      await expect(page.getByText(/Подтверждение email/i)).toHaveCount(0);
    });

    test("кнопка resend становится недоступной с обратным отсчётом после клика", async ({
      page,
    }) => {
      // TODO: войти как ученик с неподтверждённым email.
      await page.goto("/student/cabinet/schedule");

      await expect(
        page.getByRole("button", { name: "Отправить заново" })
      ).toBeEnabled();

      await page.getByRole("button", { name: "Отправить заново" }).click();

      // 60-секундный cooldown тикает внутри модели; кнопка должна быть disabled
      // и показывать «Отправить заново через NNс».
      await expect(
        page.getByRole("button", { name: /Отправить заново через \d+с/ })
      ).toBeDisabled();
    });
  }
);
