// Draft generated by /e2e-check on 2026-05-20. Refine selectors and assertions, then remove @draft tag and rename to .spec.ts
import { expect, test } from "@playwright/test";

test.describe(
  "Логин ученика через переключатель Преподаватель/Ученик",
  { tag: ["@draft", "@critical", "@auth"] },
  () => {
    test("ученик переключает роль на /login и попадает в свой кабинет", async ({
      page,
    }) => {
      // TODO: подготовить зарегистрированного StudentUser через REST (issueInvitation +
      // registerStudentByInvite) — пароль `StrongPass1`, email сохранить в переменную.
      const studentEmail = "TODO_REGISTERED_STUDENT@example.com";
      const studentPassword = "StrongPass1";

      await page.goto("/login");

      // По умолчанию активен toggle «Преподаватель» — переключаем на «Ученик».
      // TODO: подобрать стабильный селектор для toggle (getByRole('button',
      // { name: 'Ученик' }) должно работать — это <ToggleButton value="student">).
      await page.getByRole("button", { name: "Ученик" }).click();

      await page.getByLabel("Email").fill(studentEmail);
      await page.getByLabel("Пароль").fill(studentPassword);
      await page.getByRole("button", { name: "Войти" }).click();

      await expect(page).toHaveURL(/\/student\/cabinet\/schedule$/);
    });

    test("ученик не может зайти как преподаватель тем же email/паролем", async ({
      page,
    }) => {
      // Регрессия: cross-role security — пароль StudentUser не должен открывать tutor-flow.
      const studentEmail = "TODO_REGISTERED_STUDENT@example.com";
      const studentPassword = "StrongPass1";

      await page.goto("/login");
      // Преподаватель — это активный toggle по умолчанию, переключать не нужно.

      await page.getByLabel("Email").fill(studentEmail);
      await page.getByLabel("Пароль").fill(studentPassword);
      await page.getByRole("button", { name: "Войти" }).click();

      // Должно показать ошибку аутентификации, а не редирект в tutor-кабинет.
      await expect(page.getByRole("alert")).toBeVisible();
      await expect(page).not.toHaveURL(/^.*\/$/);
    });
  }
);
